; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = https://github.com/pioarduino/platform-espressif32.git
board = upesy_wroom
framework = arduino
monitor_speed = 921600
build_flags =
    -D USER_SETUP_LOADED=1
    -include include/User_Setup.h
    -D ARDUINOJSON_ENABLE_COMMENTS=0
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    mathieucarbou/AsyncTCP @ ^3.2.14
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    ricmoo/QRCode @ ^0.0.1
    bodmer/TFT_eSPI @ ^2.5.43
